{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    app.kubernetes.io/name: {{ .Chart.Name }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: stockdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: stockdevops
spec:
  ports:
    - port: 6379
      targetPort: redis
      name: redis
  selector:
    app: {{ .Release.Name }}-redis
{{- end }}
