apiVersion: v1
kind: Secret
metadata:
  name: stockdevops-db-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: stockdevops
type: Opaque
data:
  # Base64 encoded connection string to PostgreSQL:
  # postgresql://stockforge:stockforge_prod_db_pass@stockdevops-db:5432/stockforge_ai
  database-url: cG9zdGdyZXNxbDovL3N0b2NrZm9yZ2U6c3RvY2tmb3JnZV9wcm9kX2RiX3Bhc3NAdXNlci1kYjo1NDMyL3N0b2NrZm9yZ2VfYWk=
  
  # Base64 encoded secure 64-char hex key for JWT encryption:
  jwt-access-secret: NGVhNjI5NmU4NDExM2M3ZTdkMDdmZDFiMjI4Zjk2NWI4NjI4NTQ5NTY3ZmU3MmE4YzZlYzc1N2U3OGNiNWIwYQ==
  jwt-refresh-secret: NThmZjA4MDgzMDdkNjI0NmM3NTQ1YTU5MzcwYmNjOWZmYmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZg==
