apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: stockdevops-monitoring
spec:
  type: ClusterIP # Internal communication only (Grafana scrapes logs from here)
  selector:
    app: loki
  ports:
  - name: http
    port: 3100
    targetPort: 3100
  - name: grpc
    port: 9096
    targetPort: 9096
