apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: stockdevops-monitoring
spec:
  type: NodePort # Exposed externally for ease of management on EC2
  selector:
    app: prometheus-server
  ports:
  - name: web
    port: 9090
    targetPort: 9090
    nodePort: 30090 # Access via http://<EC2-IP>:30090
