apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ci-cd
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: stockdevops-ci-cd
spec:
  type: NodePort # Allows external access via EC2 public IP
  selector:
    app: jenkins
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080 # Clean, fixed NodePort for external access (EC2 IP:30080)
  - name: agent
    port: 50000
    targetPort: 50000
    # No NodePort for agent, it is purely internal ClusterIP communication
