apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
  namespace: ci-cd
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: stockdevops-ci-cd
    app.kubernetes.io/component: ci-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: stockdevops-gp3-sc # Dynamically provisioned gp3 EBS volume
  resources:
    requests:
      storage: 15Gi # Generous volume for build artifacts, plugins, and job history
