apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stockdevops-ci-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/mohammedmusa1/stock_Devops.git" # Replaced dynamically by setup.sh
    targetRevision: HEAD # Replaced dynamically by setup.sh
    path: gitops/apps/ci-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
